<a href="https://colab.research.google.com/github/mithilesh-p/Fake-Job-Prediction/blob/main/Fake_Job_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **IMPORTING IMPOTANT LIBRARIES**

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import joblib
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import linear_model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
modell= LogisticRegression()

from sklearn.metrics import confusion_matrix

from sklearn import tree
modeld=tree.DecisionTreeClassifier()

from sklearn.svm import SVC
models=SVC()

from sklearn.ensemble import RandomForestClassifier
modelr=RandomForestClassifier()

from sklearn.model_selection import cross_val_score

from sklearn.cluster import KMeans

from sklearn.preprocessing import MinMaxScaler

from sklearn.naive_bayes import GaussianNB
modelg=GaussianNB()

from sklearn.naive_bayes import MultinomialNB
modelm=MultinomialNB()

from sklearn.pipeline import Pipeline

from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()

from sklearn.model_selection import GridSearchCV

from sklearn.model_selection import RandomizedSearchCV

## IMPORTING THE DATA 

In [ ]:
df1=pd.read_csv("/content/fake_job_postings.csv")
df1.head()

job_id                                      title            location  \
0       1                           Marketing Intern    US, NY, New York   
1       2  Customer Service - Cloud Video Production      NZ, , Auckland   
2       3    Commissioning Machinery Assistant (CMA)       US, IA, Wever   
3       4          Account Executive - Washington DC  US, DC, Washington   
4       5                        Bill Review Manager  US, FL, Fort Worth   

  department salary_range                                    company_profile  \
0  Marketing          NaN  We're Food52, and we've created a groundbreaki...   
1    Success          NaN  90 Seconds, the worlds Cloud Video Production ...   
2        NaN          NaN  Valor Services provides Workforce Solutions th...   
3      Sales          NaN  Our passion for improving quality of life thro...   
4        NaN          NaN  SpotSource Solutions LLC is a Global Human Cap...   

                                         description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Rese...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  \
0  Experience with content management systems a m...   
1  What we expect from you:Your key responsibilit...   
2  Implement pre-commissioning and commissioning ...   
3  EDUCATION: Bachelor’s or Master’s in GIS, busi...   
4  QUALIFICATIONS:RN license in the State of Texa...   

                                            benefits  telecommuting  \
0                                                NaN              0   
1  What you will get from usThrough being part of...              0   
2                                                NaN              0   
3  Our culture is anything but corporate—we have ...              0   
4                              Full Benefits Offered              0   

   has_company_logo  has_questions employment_type required_experience  \
0                 1              0           Other          Internship   
1                 1              0       Full-time      Not Applicable   
2                 1              0             NaN                 NaN   
3                 1              0       Full-time    Mid-Senior level   
4                 1              1       Full-time    Mid-Senior level   

  required_education                   industry              function  \
0                NaN                        NaN             Marketing   
1                NaN  Marketing and Advertising      Customer Service   
2                NaN                        NaN                   NaN   
3  Bachelor's Degree          Computer Software                 Sales   
4  Bachelor's Degree     Hospital & Health Care  Health Care Provider   

   fraudulent  
0           0  
1           0  
2           0  
3           0  
4           0

In [ ]:
df=df1[['description','fraudulent']]
df.head()

description  fraudulent
0  Food52, a fast-growing, James Beard Award-winn...           0
1  Organised - Focused - Vibrant - Awesome!Do you...           0
2  Our client, located in Houston, is actively se...           0
3  THE COMPANY: ESRI – Environmental Systems Rese...           0
4  JOB TITLE: Itemization Review ManagerLOCATION:...           0

In [ ]:
###Drop Nan Values
df=df.dropna()

In [ ]:
## Get the Independent Features

X=df.drop('fraudulent',axis=1)

In [ ]:
## Get the Dependent features
y=df['fraudulent']

In [ ]:
y.value_counts()

0    17014
1      865
Name: fraudulent, dtype: int64

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [ ]:
message = X.copy()

In [ ]:
message.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

**STEMMING OPERATION**

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['description'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [ ]:
corpus[1]

'organis focus vibrant awesom passion custom servic slick type skill mayb account manag think administr cooler polar bear jetski need hear cloud video product servic opper glodal level yeah pretti cool seriou deliv world class product excel custom servic rapidli expand busi look talent project manag manag success deliveri video project manag client commun drive product process work coolest brand planet learn global team repres nz huge way enter next growth stage busi grow quickli intern therefor posit burst opportun right person enter busi right time second world cloud video product servic http url fbe afac cd c f b eef e e f ca dd second world cloud video product servic enabl brand agenc get high qualiti onlin video content shot produc anywher world fast afford manag seamlessli cloud purchas publish second remov hassl cost risk speed issu work regular video product compani manag everi aspect video project beauti onlin experi grow network rate video profession countri dedic product suc

In [ ]:
len(corpus)

17879

In [ ]:
message.shape

(17879, 2)

In [ ]:
message.description=corpus

In [ ]:
message.head()

index                                        description
0      0  food fast grow jame beard award win onlin food...
1      1  organis focus vibrant awesom passion custom se...
2      2  client locat houston activ seek experienc comm...
3      3  compani esri environment system research insti...
4      4  job titl item review managerloc fort worth tx ...

# One Hot Representation

In [ ]:
pip install keras-tuner --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 135 kB 18.8 MB/s 
     |████████████████████████████████| 1.6 MB 36.7 MB/s 


In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import keras_tuner as kt

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM

In [ ]:
voc_size=5000

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr[1]

[2739,
 1537,
 4995,
 541,
 1610,
 730,
 3826,
 4651,
 2248,
 407,
 1655,
 3344,
 3729,
 964,
 914,
 4848,
 3406,
 2030,
 2884,
 4819,
 2977,
 4781,
 2319,
 2443,
 3826,
 2830,
 2121,
 4954,
 4227,
 4379,
 554,
 536,
 2076,
 3546,
 534,
 2443,
 1215,
 730,
 3826,
 467,
 349,
 459,
 2037,
 1314,
 3056,
 3729,
 3729,
 1139,
 3308,
 2319,
 3056,
 3729,
 2696,
 4085,
 4049,
 2443,
 4958,
 1438,
 1788,
 3130,
 1746,
 1073,
 2552,
 3266,
 2490,
 4755,
 361,
 2391,
 2201,
 4927,
 1952,
 2697,
 459,
 1128,
 1423,
 2323,
 1260,
 1321,
 2686,
 2234,
 4090,
 317,
 2201,
 459,
 4090,
 3858,
 4111,
 3546,
 4781,
 2319,
 2443,
 3826,
 2018,
 2967,
 4471,
 1523,
 4642,
 2346,
 543,
 3079,
 1524,
 1500,
 1500,
 543,
 812,
 980,
 4111,
 3546,
 4781,
 2319,
 2443,
 3826,
 1334,
 3130,
 2943,
 4395,
 3598,
 893,
 4591,
 2319,
 868,
 3027,
 15,
 3077,
 3546,
 2137,
 1392,
 3729,
 3418,
 4781,
 1807,
 2191,
 4111,
 4538,
 1938,
 1755,
 4453,
 4512,
 3588,
 1438,
 2683,
 2319,
 2443,
 3201,
 3729,
 2242,
 3

## **PADDING THE ONE HOT REPRESENTATION**

In [ ]:
sent_length=40
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[4025  868 3729 ... 2030 2116 4895]
 [1139 3065 3096 ... 3666  823 1024]
 [   0    0    0 ...  609 3923 1911]
 ...
 [3825 2987  776 ... 2214  744 3720]
 [4979 4331 4020 ...  341 2323 3056]
 [2112 3153  195 ... 2445  978 2336]]


In [ ]:
message.description=np.array(embedded_docs)

In [ ]:
index=range(0,15184)

In [ ]:
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.20)

In [ ]:
emb_vec_feature=40

In [ ]:
import keras
from tensorflow.keras import layers

## **BUILDING A NEURAL NETWORK WITH FEW LAYER**

In [ ]:
embedding_vector_features=50
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100))) ##Just add bidirectional!!, except it would just behave as normal LSTM Model
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 40, 50)            250000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              120800    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense (Dense)               (None, 1)                 201       
                                                                 
Total params: 371,001
Trainable params: 371,001
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model1.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=50,batch_size=64)

Epoch 1/50
224/224 [==============================] - 34s 106ms/step - loss: 0.1795 - accuracy: 0.9553 - val_loss: 0.1019 - val_accuracy: 0.9715
Epoch 2/50
224/224 [==============================] - 20s 91ms/step - loss: 0.0868 - accuracy: 0.9750 - val_loss: 0.0960 - val_accuracy: 0.9740
Epoch 3/50
224/224 [==============================] - 21s 96ms/step - loss: 0.0595 - accuracy: 0.9829 - val_loss: 0.0915 - val_accuracy: 0.9771
Epoch 4/50
224/224 [==============================] - 20s 89ms/step - loss: 0.0462 - accuracy: 0.9855 - val_loss: 0.1052 - val_accuracy: 0.9760
Epoch 5/50
224/224 [==============================] - 22s 97ms/step - loss: 0.0285 - accuracy: 0.9922 - val_loss: 0.1234 - val_accuracy: 0.9664
Epoch 6/50
224/224 [==============================] - 21s 91ms/step - loss: 0.0210 - accuracy: 0.9931 - val_loss: 0.1332 - val_accuracy: 0.9732
Epoch 7/50
224/224 [==============================] - 20s 90ms/step - loss: 0.0147 - accuracy: 0.9960 - val_loss: 0.1448 - val_accuracy

In [ ]:
y_pred=model1.predict(x_test)
y_pred = np.round(y_pred).astype(int)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[3372,   49],
       [  55,  100]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.970917225950783

 ACCURACY IS 97% 